/* 
 * Core Investment Tracker API
 *
 * Investment tracker is a platform that allows you to track aspects that affect your investments
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// InvestmentGroupInvestment
    /// </summary>
    [DataContract]
    public partial class InvestmentGroupInvestment :  IEquatable<InvestmentGroupInvestment>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InvestmentGroupInvestment" /> class.
        /// </summary>
        /// <param name="investmentGroupID">investmentGroupID.</param>
        /// <param name="investmentGroup">investmentGroup.</param>
        /// <param name="investmentID">investmentID.</param>
        /// <param name="investment">investment.</param>
        public InvestmentGroupInvestment(int? investmentGroupID = default(int?), InvestmentGroup investmentGroup = default(InvestmentGroup), int? investmentID = default(int?), Investment investment = default(Investment))
        {
            this.InvestmentGroupID = investmentGroupID;
            this.InvestmentGroup = investmentGroup;
            this.InvestmentID = investmentID;
            this.Investment = investment;
        }
        
        /// <summary>
        /// Gets or Sets InvestmentGroupID
        /// </summary>
        [DataMember(Name="investmentGroupID", EmitDefaultValue=false)]
        public int? InvestmentGroupID { get; set; }

        /// <summary>
        /// Gets or Sets InvestmentGroup
        /// </summary>
        [DataMember(Name="investmentGroup", EmitDefaultValue=false)]
        public InvestmentGroup InvestmentGroup { get; set; }

        /// <summary>
        /// Gets or Sets InvestmentID
        /// </summary>
        [DataMember(Name="investmentID", EmitDefaultValue=false)]
        public int? InvestmentID { get; set; }

        /// <summary>
        /// Gets or Sets Investment
        /// </summary>
        [DataMember(Name="investment", EmitDefaultValue=false)]
        public Investment Investment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InvestmentGroupInvestment {\n");
            sb.Append("  InvestmentGroupID: ").Append(InvestmentGroupID).Append("\n");
            sb.Append("  InvestmentGroup: ").Append(InvestmentGroup).Append("\n");
            sb.Append("  InvestmentID: ").Append(InvestmentID).Append("\n");
            sb.Append("  Investment: ").Append(Investment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InvestmentGroupInvestment);
        }

        /// <summary>
        /// Returns true if InvestmentGroupInvestment instances are equal
        /// </summary>
        /// <param name="input">Instance of InvestmentGroupInvestment to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InvestmentGroupInvestment input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InvestmentGroupID == input.InvestmentGroupID ||
                    (this.InvestmentGroupID != null &&
                    this.InvestmentGroupID.Equals(input.InvestmentGroupID))
                ) && 
                (
                    this.InvestmentGroup == input.InvestmentGroup ||
                    (this.InvestmentGroup != null &&
                    this.InvestmentGroup.Equals(input.InvestmentGroup))
                ) && 
                (
                    this.InvestmentID == input.InvestmentID ||
                    (this.InvestmentID != null &&
                    this.InvestmentID.Equals(input.InvestmentID))
                ) && 
                (
                    this.Investment == input.Investment ||
                    (this.Investment != null &&
                    this.Investment.Equals(input.Investment))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InvestmentGroupID != null)
                    hashCode = hashCode * 59 + this.InvestmentGroupID.GetHashCode();
                if (this.InvestmentGroup != null)
                    hashCode = hashCode * 59 + this.InvestmentGroup.GetHashCode();
                if (this.InvestmentID != null)
                    hashCode = hashCode * 59 + this.InvestmentID.GetHashCode();
                if (this.Investment != null)
                    hashCode = hashCode * 59 + this.Investment.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
