/* 
 * Core Investment Tracker API
 *
 * Investment tracker is a platform that allows you to track aspects that affect your investments
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CustomEntityInvestment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomEntityInvestmentTests
    {
        // TODO uncomment below to declare an instance variable for CustomEntityInvestment
        //private CustomEntityInvestment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomEntityInvestment
            //instance = new CustomEntityInvestment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomEntityInvestment
        /// </summary>
        [Test]
        public void CustomEntityInvestmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomEntityInvestment
            //Assert.IsInstanceOfType<CustomEntityInvestment> (instance, "variable 'instance' is a CustomEntityInvestment");
        }


        /// <summary>
        /// Test the property 'CustomEntityId'
        /// </summary>
        [Test]
        public void CustomEntityIdTest()
        {
            // TODO unit test for the property 'CustomEntityId'
        }
        /// <summary>
        /// Test the property 'CustomEntity'
        /// </summary>
        [Test]
        public void CustomEntityTest()
        {
            // TODO unit test for the property 'CustomEntity'
        }
        /// <summary>
        /// Test the property 'InvestmentID'
        /// </summary>
        [Test]
        public void InvestmentIDTest()
        {
            // TODO unit test for the property 'InvestmentID'
        }
        /// <summary>
        /// Test the property 'Investment'
        /// </summary>
        [Test]
        public void InvestmentTest()
        {
            // TODO unit test for the property 'Investment'
        }

    }

}
