/* 
 * Core Investment Tracker API
 *
 * Investment tracker is a platform that allows you to track aspects that affect your investments
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InvestmentRiskInvestment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InvestmentRiskInvestmentTests
    {
        // TODO uncomment below to declare an instance variable for InvestmentRiskInvestment
        //private InvestmentRiskInvestment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InvestmentRiskInvestment
            //instance = new InvestmentRiskInvestment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InvestmentRiskInvestment
        /// </summary>
        [Test]
        public void InvestmentRiskInvestmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InvestmentRiskInvestment
            //Assert.IsInstanceOfType<InvestmentRiskInvestment> (instance, "variable 'instance' is a InvestmentRiskInvestment");
        }


        /// <summary>
        /// Test the property 'InvestmentRiskID'
        /// </summary>
        [Test]
        public void InvestmentRiskIDTest()
        {
            // TODO unit test for the property 'InvestmentRiskID'
        }
        /// <summary>
        /// Test the property 'InvestmentRisk'
        /// </summary>
        [Test]
        public void InvestmentRiskTest()
        {
            // TODO unit test for the property 'InvestmentRisk'
        }
        /// <summary>
        /// Test the property 'InvestmentID'
        /// </summary>
        [Test]
        public void InvestmentIDTest()
        {
            // TODO unit test for the property 'InvestmentID'
        }
        /// <summary>
        /// Test the property 'Investment'
        /// </summary>
        [Test]
        public void InvestmentTest()
        {
            // TODO unit test for the property 'Investment'
        }

    }

}
