/* 
 * Core Investment Tracker API
 *
 * Investment tracker is a platform that allows you to track aspects that affect your investments
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InvestmentNote
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InvestmentNoteTests
    {
        // TODO uncomment below to declare an instance variable for InvestmentNote
        //private InvestmentNote instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InvestmentNote
            //instance = new InvestmentNote();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InvestmentNote
        /// </summary>
        [Test]
        public void InvestmentNoteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InvestmentNote
            //Assert.IsInstanceOfType<InvestmentNote> (instance, "variable 'instance' is a InvestmentNote");
        }


        /// <summary>
        /// Test the property 'InvestmentIds'
        /// </summary>
        [Test]
        public void InvestmentIdsTest()
        {
            // TODO unit test for the property 'InvestmentIds'
        }
        /// <summary>
        /// Test the property 'OwningEntityId'
        /// </summary>
        [Test]
        public void OwningEntityIdTest()
        {
            // TODO unit test for the property 'OwningEntityId'
        }
        /// <summary>
        /// Test the property 'OwningEntityType'
        /// </summary>
        [Test]
        public void OwningEntityTypeTest()
        {
            // TODO unit test for the property 'OwningEntityType'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'CreatedTime'
        /// </summary>
        [Test]
        public void CreatedTimeTest()
        {
            // TODO unit test for the property 'CreatedTime'
        }
        /// <summary>
        /// Test the property 'LastModifiedTime'
        /// </summary>
        [Test]
        public void LastModifiedTimeTest()
        {
            // TODO unit test for the property 'LastModifiedTime'
        }
        /// <summary>
        /// Test the property 'Points'
        /// </summary>
        [Test]
        public void PointsTest()
        {
            // TODO unit test for the property 'Points'
        }
        /// <summary>
        /// Test the property 'IsFlagged'
        /// </summary>
        [Test]
        public void IsFlaggedTest()
        {
            // TODO unit test for the property 'IsFlagged'
        }

    }

}
