/* 
 * Core Investment Tracker API
 *
 * Investment tracker is a platform that allows you to track aspects that affect your investments
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Investment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InvestmentTests
    {
        // TODO uncomment below to declare an instance variable for Investment
        //private Investment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Investment
            //instance = new Investment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Investment
        /// </summary>
        [Test]
        public void InvestmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Investment
            //Assert.IsInstanceOfType<Investment> (instance, "variable 'instance' is a Investment");
        }


        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'ValueProposition'
        /// </summary>
        [Test]
        public void ValuePropositionTest()
        {
            // TODO unit test for the property 'ValueProposition'
        }
        /// <summary>
        /// Test the property 'DesirabilityStatement'
        /// </summary>
        [Test]
        public void DesirabilityStatementTest()
        {
            // TODO unit test for the property 'DesirabilityStatement'
        }
        /// <summary>
        /// Test the property 'InitialInvestment'
        /// </summary>
        [Test]
        public void InitialInvestmentTest()
        {
            // TODO unit test for the property 'InitialInvestment'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Factors'
        /// </summary>
        [Test]
        public void FactorsTest()
        {
            // TODO unit test for the property 'Factors'
        }
        /// <summary>
        /// Test the property 'Regions'
        /// </summary>
        [Test]
        public void RegionsTest()
        {
            // TODO unit test for the property 'Regions'
        }
        /// <summary>
        /// Test the property 'Risks'
        /// </summary>
        [Test]
        public void RisksTest()
        {
            // TODO unit test for the property 'Risks'
        }
        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Test]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }
        /// <summary>
        /// Test the property 'CustomEntities'
        /// </summary>
        [Test]
        public void CustomEntitiesTest()
        {
            // TODO unit test for the property 'CustomEntities'
        }
        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Test]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }
        /// <summary>
        /// Test the property 'InvestmentIds'
        /// </summary>
        [Test]
        public void InvestmentIdsTest()
        {
            // TODO unit test for the property 'InvestmentIds'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'CreatedTime'
        /// </summary>
        [Test]
        public void CreatedTimeTest()
        {
            // TODO unit test for the property 'CreatedTime'
        }
        /// <summary>
        /// Test the property 'LastModifiedTime'
        /// </summary>
        [Test]
        public void LastModifiedTimeTest()
        {
            // TODO unit test for the property 'LastModifiedTime'
        }
        /// <summary>
        /// Test the property 'Points'
        /// </summary>
        [Test]
        public void PointsTest()
        {
            // TODO unit test for the property 'Points'
        }
        /// <summary>
        /// Test the property 'IsFlagged'
        /// </summary>
        [Test]
        public void IsFlaggedTest()
        {
            // TODO unit test for the property 'IsFlagged'
        }

    }

}
